<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SpyVsSpy.Wpf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\libSpyCore\libSpyCore.csproj" />
  </ItemGroup>

</Project>
